app/controllers.py
from flask import request, render_template, Blueprint, json, redirect, url_for, flash
from app import db, login_manager
from app.heidi.dataset.api import readDataset
from models import User
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_required, login_user, current_user, logout_user
import random
import os
import pandas as pd
from config import DevelopmentConfig as config
from mod_datacleaning import data_cleaning
import app.heidi.api as hd
import app.heidi.database.api as db
from flask import jsonify
import linecache
import sys

def PrintException():
    exc_type, exc_obj, tb = sys.exc_info()
    f = tb.tb_frame
    lineno = tb.tb_lineno
    filename = f.f_code.co_filename
    linecache.checkcache(filename)
    line = linecache.getline(filename, lineno, f.f_globals)
    print ('EXCEPTION IN ({}, LINE {} "{}"): {}'.format(filename, lineno, line.strip(), exc_obj))
    return ('EXCEPTION IN ({}, LINE {} "{}"): {}'.format(filename, lineno, line.strip(), exc_obj))

mod_controllers = Blueprint('controllers', __name__)

#To create new user (name, phone number, password) and save it in database
@mod_controllers.route('/register', methods=['POST', 'GET'])
def register():
    if request.method == 'POST':
        try:
            user = User(request.form['name'], request.form['phone'], generate_password_hash(
                request.form['password'], method='sha256'), request.form['email'])
            db.session.add(user)
            db.session.commit()
            return redirect(url_for('controllers.login'))
        except Exception as e:
            print(e)
            flash('Wrong inputs, please check your input and try again.')
            return render_template('register.html', user=current_user)
    else:
        return render_template('register.html', user=current_user)


@login_manager.user_loader
def load_user(user_id):
    try:
        return User.query.get(int(user_id))
    except:
        return None


@mod_controllers.route('/login', methods=['POST', 'GET'])
def login():
    if request.method == 'GET':
        if not current_user.is_anonymous:
            return render_template('index.html', user=current_user)
        return render_template('login.html', user=current_user)
    else:
        user = User.query.filter(User.email == request.form['email']).first()
        if user:
            if check_password_hash(user.password, request.form['password']):
                login_user(user)
                return render_template('index.html', user=current_user)
            else:
                flash('Wrong password.')
                return render_template('login.html', user=current_user)
        else:
            flash('Username doesn\'t exist.')
            return render_template('login.html', user=current_user)


@mod_controllers.route('/logout', methods=['GET'])
@login_required
def logout():
    logout_user()
    return redirect(url_for('controllers.index'))


@mod_controllers.route('/', methods=['GET'])
def index():
    return render_template('index.html', user=current_user)


@mod_controllers.route('/upload', methods=['POST'])
def upload():
    try:
        file = request.files['file']
        filename = file.filename
        if filename=='':
            raise ValueError('No file uploaded!!')
        file_uploads_path = os.path.join(config.UPLOADS_DIR, filename)
        file_static_path = os.path.join(config.STATIC_DIR, 'output')
        file_static_path = os.path.join(file_static_path, filename)
        file.save(file_uploads_path)
        if (filename.rsplit('.', 1)[1].lower() == 'csv'):
            dirty_file = pd.read_csv(file_uploads_path, sep=',')
            res = data_cleaning.id_classLabel_check(dirty_file)
            if(res!=True):
                raise ValueError(res)
            missing_val_fixed_file = data_cleaning.fix_missing(dirty_file, request.form['fix'])
            cleaned_file = data_cleaning.clean(missing_val_fixed_file)
            cleaned_file.to_csv(file_uploads_path, sep=',',index=False)
        elif (filename.rsplit('.', 1)[1].lower() == 'tsv'):
            dirty_file = pd.read_csv(file_uploads_path, sep='\t')
            missing_val_fixed_file = data_cleaning.fix_missing(
                dirty_file, request.form['fix'])
            cleaned_file = data_cleaning.clean(missing_val_fixed_file)
            cleaned_file.to_csv(file_uploads_path, sep=',',index=False)
        elif (filename.rsplit('.', 1)[1].lower() == 'json'):
            print (str(file_uploads_path))
            dirty_file = pd.read_json(str(file_uploads_path))
            missing_val_fixed_file = data_cleaning.fix_missing(
                dirty_file, request.form['fix'])
            cleaned_file = data_cleaning.clean(missing_val_fixed_file)
            cleaned_file.to_json(file_uploads_path)
        else:
            raise ValueError('Invalid file input! Please check the input file type')

        download_path = 'static/uploads/' + filename
        
        robj = readDataset(download_path)
        db.saveDatasetToDB(download_path)
        hd.createAndSaveMatrixToDB(download_path, 10)
        response_data = {
            'status': 'success',
            'datasetPath': download_path,
            'url': '/columns',  # This should be the URL for the columns display page
            
        }
        return jsonify(response_data)
    
        # return render_template('success.html', download_path=download_path, user=current_user)
        # return render_template('first.html',title='visual tool',datasetPath=download_path, user=current_user)
    except Exception as e:
        print(e)
        PrintException()
        flash(PrintException())
        return render_template('index.html', user=current_user)

@mod_controllers.route('/contact', methods=['GET'])
def contact():
    print(current_user.name)
    return render_template('contact.html', user=current_user)


@login_required
@mod_controllers.route('/account', methods=['GET', 'POST'])
def account():
    if request.method == 'GET':
        colors = ['primary', 'success', 'info', 'warning', 'danger']
        return render_template('account.html', user=current_user, color=random.choice(colors))
    else:
        try:
            if check_password_hash(current_user.password, request.form['oldpassword']):
                current_user.password = generate_password_hash(
                    request.form['newpassword'], method='sha256')
                db.session.commit()
                return redirect(url_for('controllers.index'))
            else:
                flash('Enter current password correctly and try again.')
                return redirect(url_for('controllers.account'))
        except:
            flash('Some error occurred, please try again later.')
            return redirect(url_for('controllers.account'))

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>{% block title %}{% endblock %} | Intensive Visual Analytics Tool</title>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{{ url_for('static',filename='css/dist/bootstrap.min.css') }}">
    
    <!--<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">-->
  
    {% block import %}
    {% endblock %}
  </head>
  <body style="background-color: #fcfcfc;">
    <nav class="navbar navbar-toggleable-md navbar-inverse bg-primary bg-faded sticky-top">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand" href="{{ url_for('controllers.index') }}">Intensive Visual Analytics Tool</a>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item {% block active_index %}{% endblock %}">
            <a class="nav-link" href="{{ url_for('controllers.index') }}">Home</a>
          </li>
          <li class="nav-item {% block active_contact %}{% endblock %}">
            <a class="nav-link" href="{{ url_for('controllers.contact') }}">Contact Us</a>
          </li>
          {% if user.is_authenticated %}
          <li class="nav-item dropdown {% block active_account %}{% endblock %}">
            <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              {{ user.name }}
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <a class="dropdown-item" href="{{ url_for('controllers.account') }}">My Account</a>
              <a class="dropdown-item" href="{{ url_for('controllers.logout') }}">Logout</a>
            </div>
          </li>    
          {% else %}
          <li class="nav-item {% block active_login %}{% endblock %}">
            <a class="nav-link" href="{{ url_for('controllers.login') }}">Login</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </nav>

    <div class="container mt-5">
      {% block content %}
      {% endblock %}
    </div>
      {% block content1 %}
      {% endblock %}
    <!-- jQuery first, then Tether, then Bootstrap JS. -->
    <script src="{{ url_for('static',filename='js/dist/jquery.min.js') }}"></script>
  
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
    <script src="{{ url_for('static',filename='js/dist/bootstrap.min.js') }}"></script>
    {% block jsimport %}
    {% endblock %}
	</body>
</html>

app/templates/contact.html
{% extends 'base.html' %}

{% block title %}
Contact Us
{% endblock %}

{% block active_contact %}
active
{% endblock %}

{% block content %}
      <div class="container jumbotron" style="background-color: rgba(0.7,0.7,0.7,0.2)">
        <h2 class="text-info">Contact us</h2>
        <p>
          Submit your query or feedback here and hold back! We'll contact you.
        </p>
        <form>
          <div class="form-group">
            <label for="email">Email address</label>
            <input type="email" class="form-control" id="email" aria-describedby="emailHelp" placeholder="Enter email">
            <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
          </div>
          <div class="form-group">
            <label for="message">Message</label>
            <textarea class="form-control" id="message" rows="3"></textarea>
          </div>
          <button type="submit" class="btn btn-info">Submit</button>
        </form>
      </button>
{% endblock %}

app/templates/dimension.html
{% extends 'base.html' %}

{% block title %}
Home
{% endblock %}

{% block import %}
  <link href="{{ url_for('static',filename='css/dist/googleapi_lato.css') }}" rel="stylesheet" type="text/css">
  <link rel="shortcut icon" type="image/x-icon" href="docs/images/favicon.ico" />
  <link rel="stylesheet" href="{{ url_for('static',filename='css/dist/leaflet.css') }}"/>
<!--  <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='css/maincss.css') }}" />-->
  <script src="{{ url_for('static',filename='js/dist/leaflet.js') }}" ></script>
  <script src="{{ url_for('static',filename='js/dist/d3.v3.js') }}"></script>
  <script src="{{ url_for('static',filename='js/dist/plotly-latest.min.js') }}"></script>
  <script src="{{ url_for('static',filename='js/vis3.js') }}"></script>
  <script src="{{ url_for('static',filename='js/vis4.js') }}"></script>
  <script src="{{ url_for('static',filename='js/giant-wheel.js') }}"></script>
  <script src="{{ url_for('static',filename='js/dimension.js') }}"></script>
{% endblock %}

{% block active_index %}
active
{% endblock %}

{% block content1 %}
  <!-- Container (Services Section) -->
  <div class="container-fluid text-center">
    <h4>Dataset :  '{{ datasetPath }}'</h4>
    <h4> Starting Dimension</h4>
    <button id="gobutton"> GO</button>
    <button id="resetButton"> Reset Image </button>
    <div>Show Grid? <input type="radio" value="yes" name="grid">yes
      <input type="radio" value="no" name="grid">no</div>
    <div id="dimlist2">
    </div>
    <div id="filterlist">
    </div>
    <br>
    <div class="row text-left" style="text-align:right display:inline;" >
      <!--<select id='changeImgType'>
        <option value="heidi"> Heidi Image</option>
        <option value="composite">Composite Image</option>
        <option value="closed">Closed Image</option>
      </select>-->
    </div>
    <br/>
    <div class="row text-left" style="text-align:right display:inline;" >
      Analyze patterns grid wise ? <input type="radio" value="yes" name="ptype">yes
      <input type="radio" value="no" name="ptype">no
    </div>
    <div class="row text-left" style="text-align:right display:inline;" >
      KNN <input type="text" value="" name="knn" id="knn">
    </div>
    <div class="row" align="right" style="text-align:right display:inline;" >
    <form action={{ url_for('heidicontrollers.pattern_dashboard') }}>
    <input type="hidden" name="datasetName" value="{{datasetPath}}"></input>
    <button type="submit" align="right" class="btn" >Pattern Dashboard</button>
    </form>
    <form action={{ url_for('heidicontrollers.analyticsReport') }}>
    <input type="hidden" name="datasetName" value="{{datasetPath}}"></input>
    <button type="submit" align="right" class="btn" >Analytics Report</button>
    </form>
    </div>
    <!--<div class="row text-right" style="text-align:right display:inline;" >
      <button id="dashboard">Subspace Dashboard </button>
    </div>-->
    <div class="alert_msg" style="display: none;">
      <div class="alert alert-danger alert-dismissible" role="alert" >
      <strong>ERROR!!</strong><p class="error_msg"></p>
    </div>

    </div>

    <br/>
    <div id="loading"></div>
    <div class="row">
      <div class="col-md-2">
        <h6> ADD DIMENSION</h6>
        <div id="dimlist" class="checkbox">
        </div>
      </div>
      <div class="col-md-10">
      <ul class="nav nav-tabs" id="myTab" role="tablist">
  <li class="nav-item">
    <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">Heidi</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">Closed heidi</a>
  </li>
</ul>

<div class="tab-content" id="myTabContent">
  <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
        <div class="row">
          <div class="col-md-5">
            <div id='parent' style="width: 500px; height: 400px;"></div>
          </div>
          <div class="col-md-5">
            <div id='parent2' style="width: 500px; height: 400px;"></div>
          </div>
          <div class="col-md-2">
            <div id="legend" style="overflow:scroll; height:400px;"></div>
          </div>
        </div>
  </div>
  <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
    <div class="row">
      <div class="col-md-5">
        <div id='parent3' style="width: 500px; height: 400px;"></div>
      </div>
      <div class="col-md-5">
        <div id='parent4' style="width: 500px; height: 400px;"></div>
      </div>
      <div class="col-md-2">
        <div id="legend2" style="overflow:scroll; height:400px;"></div>
      </div>
    </div>
  </div>
</div>
</div>
    



<!--<div class="col-sm-2">
      <div id="subspace" style="overflow:scroll; height:400px;"></div>
    </div>-->
    <div class="col-sm-6">
      col points
      <div id="table2" style="overflow:scroll; height:400px;"></div>
    </div>
    <div class="col-sm-6">
      row points
      <div id="table3" style="overflow:scroll; height:400px;"></div>
    </div>
    <div class="col-sm-6">
      <div id="windrose"></div>
    </div>
    <div class="col-sm-6">
    <div id="crovhd"></div>
      <!--<div id="graph1"></div>-->
    </div>
    <div class="col-sm-4">
      <div id="graph2"></div>
    </div>
    <div class="col-sm-12">
        <div id='pointsPlots'></div>
        <div id='hoverinfo'></div>
      </div>
      <div class="col-sm-6">
        <div id='parallelPlot'></div>
      </div>


    </div>

  </div>
{% endblock %}  

{% block jsimport %}
  <script>
    dynamicallyLoadSelectList('#filterlist', '#dimlist', '#dimlist2');
    //$('#dimlist2').on('click', 'input[name=order_dim]:radio',updateImage);
    //$('#dimlist').on('click', 'input[class=dim]:checkbox',updateImage);
    $('#gobutton').on('click', updateImage);
    $('#legend').on('click', 'td.backgroundcolor', function() {
      var color_val=$(this).attr('bgcolor');
      colorFilter('mapid','mapid2','parent','parent2',color_val,'heidi');
    });
    $('#legend2').on('click', 'td.backgroundcolor', function() {
      var color_val=$(this).attr('bgcolor');
      colorFilter('mapid3','mapid4','parent3','parent4',color_val,'closed');
    });
    $('#resetButton').on('click', resetImage);
    $('#tree').on('click', uploadTree);
    
    //$('#changeImgType').on('change',changeImgType);
    //$('#dashboard').on('click',)


    //$('.dim').click(updateImage);
    //$('.order_dim').click(updateImage);
  </script>
{% endblock %}
</body>

</html>

app/templates/first.html
{% extends 'base.html' %}

{% block title %}
Home
{% endblock %}

{% block import %}
<!--
  <link href="{{ url_for('static',filename='css/dist/googleapi_montserrat.css') }}" rel="stylesheet" type="text/css">
  <link href="{{ url_for('static',filename='css/dist/googleapi_lato.css') }}" rel="stylesheet" type="text/css">
  <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='css/maincss.css') }}">
-->
{% endblock %}

{% block active_index %}
active
{% endblock %}

{% block content %}
<div class="col-sm-6">
  <h2>Different Heidi visualization techniques</h2>
</div>
        
<div class="row">
        <div class="col-md-3 col-sm-12">
          <div class="card" style="width: 15rem;height: 10rem;">
            <div class="card-block">
              <h5><a href="/heidi?datasetPath={{ datasetPath }}">Basic HEIDI Visualization (MST ordering)</a></h5>
              <p class="card-text text-center">-some info</p>
            </div>
          </div>
        </div>
        <!--
        <div class="col-md-3 col-sm-12">
          <div class="card" style="width: 15rem;height: 10rem;">
            <div class="card-block">
              <h5><a href="/heidi_closed?datasetPath={{ datasetPath }}">CLOSED HEIDI VISUALIZATION </a></h5>
              <p class="card-text text-center">-some info</p>
            </div>
          </div>
        </div>

        <div class="col-md-3 col-sm-12">
          <div class="card" style="width: 15rem;height: 10rem;">
            <div class="card-block">
        <h4><a href="/heidi_bea?datasetPath={{ datasetPath }}">BEA (HEIDI VISUALIZATION)</a></h4>
              <p class="card-text text-center">-some info</p>
            </div>
          </div>
        </div>
        <div class="col-md-3 col-sm-12">
          <div class="card" style="width: 15rem;height: 10rem;">
            <div class="card-block">
        <h4><a href="/heidi_closed_bea?datasetPath={{ datasetPath }}">BEA (CLOSED HEIDI VISUALIZATION) </a></h4>
              <p class="card-text text-center">-some info</p>
            </div>
          </div>
        </div>
        -->

</div>
<!--
<br/>
  <div class="container-fluid text-center">
    <h2>Visualize Data using Heidi- story mode</h2>
    <br>
      <div class="col-sm-3">
        <span class="glyphicon glyphicon-certificate logo-small"></span>
        <h4><a href="/story?datasetPath={{ datasetPath }}">Start</a></h4>
        <p>-</p>
      </div>
  </div>
  <div class="container-fluid text-center">
    <h2>ALL 1-d subspaces</h2>
    <br>
    <div class="row">
      
      <div class="col-md-3 col-sm-12">
          <div class="card" style="width: 15rem;height: 10rem;">
            <div class="card-block">
              <h5><a href="/subspace1d?datasetPath={{ datasetPath }}">All 1-d subspaces</a></h5>
              <p class="card-text text-center">-some info</p>
            </div>
          </div>
      </div>

      <div class="col-md-3 col-sm-12">
          <div class="card" style="width: 15rem;height: 10rem;">
            <div class="card-block">
              <h5><a href="/subspace_all?datasetPath={{ datasetPath }}">All Images</a></h5>
              <p class="card-text text-center">-some info</p>
            </div>
          </div>
      </div>

    </div>
  </div>
  -->
{% endblock %}
  

app/templates/index.html
{% extends 'base.html' %}

{% block title %}
Home
{% endblock %}

{% block active_index %}
active
{% endblock %}

{% block content %}
{% with messages = get_flashed_messages() %}
{% if messages %}
{% for message in messages %}
<div class="alert alert-danger" role="alert">
  <p>{{ message }}</p>
</div>
{% endfor %}
{% endif %}
{% endwith %}
      <div class="row">
        <div class="col-md-4 col-sm-12">
          <div class="card" style="width: 20rem;">
            <div class="card-block">
              <h4 class="card-title text-center text-warning">CSV</h4>
              <p class="card-text text-center">Upload your .csv file here and get it cleaned</p>
              <form action="{{ url_for('controllers.upload') }}" method="POST" enctype="multipart/form-data">
                <div class="form-group">
                  <input name="file" type="file" class="form-control-file" id="exampleInputFile" aria-describedby="fileHelp">
                  <small id="fileHelp" class="form-text text-muted">Upload your file here and click on the upload button</small>
                </div>
                <div class="form-group">
                  <label for="fix-missing">How to fix missing values?</label>
                  <select class="form-control" id="fix-missing" name="fix">
                    <option value="skip">Skip tuple/row</option>
                    <option value="mean">Replace by mean</option>
                    <option value="median">Replace by median</option>
                    <option value="max frequent">Replace by maximum frequent value</option>
                    <option value="max">Replace by maximum value</option>
                    <option value="min">Replace by minimum value</option>
                  </select>
                </div>
                <div class="text-center">
                  <button type="submit" class="btn btn-warning">Upload CSV</button>
                </div>
              </form>
            </div>
          </div>
        </div>
        <div class="col-md-4 col-sm-12">
          <div class="card" style="width: 20rem;">
            <div class="card-block">
              <h4 class="card-title text-center text-success">JSON</h4>
              <p class="card-text text-center">Upload your .json file here and get it cleaned</p>
              <form action="{{ url_for('controllers.upload') }}" method="POST" enctype="multipart/form-data">
                <div class="form-group">
                  <input name="file" type="file" class="form-control-file" id="exampleInputFile" aria-describedby="fileHelp">
                  <small id="fileHelp" class="form-text text-muted">Upload your file here and click on the upload button</small>
                </div>
                <div class="form-group">
                  <label for="fix-missing">How to fix missing values?</label>
                  <select class="form-control" id="fix-missing" name="fix">
                    <option value="skip">Skip tuple/row</option>
                    <option value="mean">Replace by mean</option>
                    <option value="median">Replace by median</option>
                    <option value="max frequent">Replace by maximum frequent value</option>
                    <option value="max">Replace by maximum value</option>
                    <option value="min">Replace by minimum value</option>
                  </select>
                </div>
                <div class="text-center">
                  <button type="submit" class="btn btn-success">Upload JSON</button>
                </div>
              </form>
            </div>
          </div>
        </div>
        <div class="col-md-4 col-sm-12">
          <div class="card" style="width: 20rem;">
            <div class="card-block">
              <h4 class="card-title text-center text-info">TSV</h4>
              <p class="card-text text-center">Upload your .tsv file here and get it cleaned</p>
              <form action="{{ url_for('controllers.upload') }}" method="POST" enctype="multipart/form-data">
                <div class="form-group">
                  <input name="file" type="file" class="form-control-file" id="exampleInputFile" aria-describedby="fileHelp">
                  <small id="fileHelp" class="form-text text-muted">Upload your file here and click on the upload button</small>
                </div>
                <div class="form-group">
                  <label for="fix-missing">How to fix missing values?</label>
                  <select class="form-control" id="fix-missing" name="fix">
                    <option value="skip">Skip tuple/row</option>
                    <option value="mean">Replace by mean</option>
                    <option value="median">Replace by median</option>
                    <option value="max frequent">Replace by maximum frequent value</option>
                    <option value="max">Replace by maximum value</option>
                    <option value="min">Replace by minimum value</option>
                  </select>
                </div>
                <div class="text-center">
                  <button type="submit" class="btn btn-info">Upload TSV</button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
{% endblock %}

app/templates/login.html
{% extends 'base.html' %}

{% block title %}
Login
{% endblock %}

{% block active_login %}
active
{% endblock %}

{% block content %}
      <div class="container jumbotron" style="background-color: rgba(0.7,0.7,0.7,0.2)">
        <h2 class="text-warning mb-4">Login</h2>
        <form action="{{ url_for('controllers.login') }}" method="POST">
          <div class="form-group">
            <label for="email">Email address</label>
            <input name="email" type="email" class="form-control" id="email" aria-describedby="emailHelp" placeholder="Enter email">
          </div>
          <div class="form-group">
            <label for="message">Password</label>
            <input name="password" type="password" class="form-control" id="password" aria-describedby="password" placeholder="Password">
          </div>
          {% with messages = get_flashed_messages() %}
          {% if messages %}
          {% for message in messages %}
          <div class="alert alert-danger" role="alert">
            {{ message }}
          </div>
          {% endfor %}
          {% endif %}
          {% endwith %}
          <p>
            <a href="{{ url_for('controllers.register') }}">New to this site, want to register?</a>
          </p>
          <button type="submit" class="btn btn-warning">Submit</button>
        </form>
      </div>
{% endblock %}

app/templates/register.html
{% extends 'base.html' %}

{% block title %}
Register
{% endblock %}

{% block active_login %}
active
{% endblock %}

{% block content %}
      <div class="container jumbotron" style="background-color: rgba(0.7,0.7,0.7,0.2)">
        <h2 class="text-success mb-4">Register</h2>
        <form action="{{ url_for('controllers.register') }}" method="POST">
          <div class="form-group">
            <label for="email">Email address</label>
            <input name="email" type="email" class="form-control" id="email" aria-describedby="emailHelp" placeholder="Enter email">
          </div>
          <div class="form-group">
            <label for="name">Name</label>
            <input name="name" type="text" class="form-control" id="name" aria-describedby="nameHelp" placeholder="Enter name">
          </div>
          <div class="form-group">
            <label for="phone">Phone</label>
            <input name="phone" type="text" class="form-control" id="phone" aria-describedby="phoneHelp" placeholder="Enter phone number">
          </div>
          <div class="form-group">
            <label for="password">Password</label>
            <input name="password" type="password" class="form-control" id="password" aria-describedby="password" placeholder="Password">
          </div>
          {% with messages = get_flashed_messages() %}
          {% if messages %}
          {% for message in messages %}
          <div class="alert alert-danger" role="alert">
            {{ message }}
          </div>
          {% endfor %}
          {% endif %}
          {% endwith %}
          <button type="submit" class="btn btn-success">Submit</button>
        </form>
      </div>
{% endblock %}